#!/bin/sh

brew update

#Download and install the dependencies
echo "Installing autoconf..."
brew install autoconf

# Check if the install worked, if not change the ownership of the directory
# and try to install again
if [ $? -eq 0 ]; then
	continue
else
	chmod u+w /usr/local/share/man/man8
	sudo chown -R $(whoami) /usr/local/share/man/man8

	brew install autoconf
fi

echo "Installing automake..."
brew install automake

echo "Installing libtool..."
brew install libtool

echo "Installing portaudio..."
brew install portaudio

echo
echo "Installing TSAL..."

#make and install TSAL
sudo autoreconf -vi

./configure

make

make install

